//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityHotel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hotel_Restor_DiplomEntities : DbContext
    {
        public Hotel_Restor_DiplomEntities()
            : base("name=Hotel_Restor_DiplomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bar> Bar { get; set; }
        public virtual DbSet<BarSupplies> BarSupplies { get; set; }
        public virtual DbSet<Cooking> Cooking { get; set; }
        public virtual DbSet<CPA> CPA { get; set; }
        public virtual DbSet<Dishes> Dishes { get; set; }
        public virtual DbSet<DrinksВar> DrinksВar { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Goest> Goest { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<NameRestaurant> NameRestaurant { get; set; }
        public virtual DbSet<Number> Number { get; set; }
        public virtual DbSet<Poslyg> Poslyg { get; set; }
        public virtual DbSet<Sklad> Sklad { get; set; }
        public virtual DbSet<SportsHall> SportsHall { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SuppliesGoods> SuppliesGoods { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trenager> Trenager { get; set; }
        public virtual DbSet<Vidil_kyx> Vidil_kyx { get; set; }
        public virtual DbSet<ZPEmployee> ZPEmployee { get; set; }
        public virtual DbSet<Zv_Bary> Zv_Bary { get; set; }
        public virtual DbSet<Cost> Cost { get; set; }
        public virtual DbSet<Restaurant> Restaurant { get; set; }
    }
}
